### ISSUE TITLE
"三个备份组织 好像都有修改了"这句话的表述不够准确哦

### ISSUE THREAD

**Issue by iseeyo** [ssrbackup/shadowsocks-rss#4]
对比几个备份后发现，实际上只有4.7.0之后的版本才是修改版，几个组织备份的SSR C# 4.7.0的都是一样的校验签名，android 3.4.0.6也是属于原版。。。望改为正确的表述，谢谢

**Comment by ssrbackup** [comment]
我修正下

shadowsocksr-backup 更新了android 版
shadowsocksrr 为新分支
shadowsocksr-rm https://github.com/shadowsocksr-rm/shadowsocksr-libev/commits/master
