### ISSUE TITLE
问一个问题

### ISSUE THREAD

**Issue by Bianfuchen** [ssrbackup/shadowsocks-rss#5]
请问破娃酱版本的ssr。安卓端和pc端最后一版版本号多少，还有哪里还能够下载到。手慢了，没有来得及收藏

**Comment by aini51478** [comment]
https://github.com/aini51478/shadowsocks-rss 发自网易邮箱大师 在2017年10月09日 21:36，Bianfuchen 写道： 请问破娃酱版本的ssr。安卓端和pc端最后一版版本号多少，还有哪里还能够下载到。手慢了，没有来得及收藏 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ssrbackup** [comment]
android最后版本 3.4.0.6 https://github.com/esdeathlove/panel-download/blob/master/ssr-android.apk?raw=true
windows最后版本 4.7.0 https://github.com/esdeathlove/panel-download/raw/master/ssr-win.7z

readme 有写
